module.exports = {
  sidebar: {
    'Getting Started': [
      'getting-started/about',
      'getting-started/install',
      'getting-started/compatible',
    ],
    Features: [
      "highlights/highlight_actions",
      "highlights/highlight_component_overriding",
      "highlights/highlight_custom_column_rendering",
      "highlights/highlight_detail_panel",
      "highlights/highlight_editable",
      "highlights/highlight_export",
      "highlights/highlight_filtering",
      "highlights/highlight_grouping",
      "highlights/highlight_localization",
      "highlights/highlight_remote_data",
      "highlights/highlight_search",
      "highlights/highlight_selection",
      "highlights/highlight_sorting",
      "highlights/highlight_styling",
      "highlights/highlight_tree_data",
    ],
    API: [
      // "api/material_table",
      {
        "Props": [
          'api/props/mt_prop_actions',
          'api/props/mt_prop_columns',
          'api/props/mt_prop_components',
          'api/props/mt_prop_data',
          'api/props/mt_prop_detailPanel',
          'api/props/mt_prop_editable',
          'api/props/mt_prop_icons',
          'api/props/mt_prop_isLoading',
          'api/props/mt_prop_localization',
          'api/props/mt_prop_onChangePage',
          'api/props/mt_prop_onChangeRowsPerPage',
          'api/props/mt_prop_onChangeColumnHidden',
          'api/props/mt_prop_onColumnDragged',
          'api/props/mt_prop_onGroupRemoved',
          'api/props/mt_prop_onOrderChange',
          'api/props/mt_prop_onRowClick',
          'api/props/mt_prop_onSelectionChange',
          'api/props/mt_prop_onTreeExpandChange',
          'api/props/mt_prop_onSearchChange',
          'api/props/mt_prop_options',
          'api/props/mt_prop_parentChildData',
          'api/props/mt_prop_style',
          'api/props/mt_prop_tableRef',
          'api/props/mt_prop_title',
        ],
        Components: [
          'api/components/component_m_table_action',
          'api/components/component_m_table_actions',
          'api/components/component_m_table_body-row',
          'api/components/component_m_table_body',
          'api/components/component_m_table_cell',
          'api/components/component_m_table_edit-field',
          'api/components/component_m_table_edit-row',
          'api/components/component_m_table_filter-row',
          'api/components/component_m_table_group-row',
          'api/components/component_m_table_groupbar',
          'api/components/component_m_table_header',
          'api/components/component_m_table_pagination',
          'api/components/component_m_table_stepped-pagination',
          'api/components/component_m_table_toolbar',
        ],
      },
    ],
  },
};