module.exports = {
  docs: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/install",
        "getting-started/breaking-changes",
        "getting-started/compatability",
        "getting-started/about",
      ],
    },
    {
      type: "category",
      label: "Material-ui v5",
      collapsed: false,
      items: ["mui-v5/using-v5"],
    },
    {
      type: "category",
      label: "API",
      collapsed: false,
      items: [
        {
          Props: [
            "api/props/mt_prop_actions",
            "api/props/columns",
            "api/props/mt_prop_components",
            "api/props/mt_prop_data",
            "api/props/mt_prop_detailPanel",
            "api/props/mt_prop_editable",
            "api/props/mt_prop_icons",
            "api/props/mt_prop_isLoading",
            "api/props/mt_prop_localization",
            "api/props/mt_prop_onChangePage",
            "api/props/mt_prop_onChangeRowsPerPage",
            "api/props/mt_prop_onChangeColumnHidden",
            "api/props/mt_prop_onColumnDragged",
            "api/props/mt_prop_onGroupRemoved",
            "api/props/mt_prop_onOrderChange",
            "api/props/mt_prop_onRowClick",
            "api/props/mt_prop_onSelectionChange",
            "api/props/mt_prop_onTreeExpandChange",
            "api/props/mt_prop_onSearchChange",
            "api/props/options",
            "api/props/mt_prop_parentChildData",
            "api/props/mt_prop_style",
            "api/props/mt_prop_tableRef",
            "api/props/mt_prop_title",
          ],
          Components: [
            "api/components/component_m_table_action",
            "api/components/component_m_table_actions",
            "api/components/component_m_table_body-row",
            "api/components/component_m_table_body",
            "api/components/component_m_table_cell",
            "api/components/component_m_table_edit-field",
            "api/components/component_m_table_edit-row",
            "api/components/component_m_table_filter-row",
            "api/components/component_m_table_group-row",
            "api/components/component_m_table_groupbar",
            "api/components/component_m_table_header",
            "api/components/component_m_table_pagination",
            "api/components/component_m_table_stepped-pagination",
            "api/components/mtabletoolbar",
          ],
        },
      ],
    },
  ],
};
